<?php $pageTitle='Visão geral'; ob_start(); ?>
<div class="page-heading"><div><span class="eyebrow">Resumo operacional</span><h1>Sua agenda, de relance</h1><p>Acompanhe o dia e encontre rapidamente o que precisa.</p></div><a class="button primary" href="<?=e(url('/agendamentos/novo'))?>"><i class="bi bi-plus-lg"></i>Novo agendamento</a></div>
<section class="metrics" aria-label="Indicadores">
<?php foreach([['Hoje',$metrics['hoje']??0,'calendar-day'],['Amanhã',$metrics['amanha']??0,'sunrise'],['Confirmados',$metrics['confirmados']??0,'check2-circle'],['Pendentes',$metrics['pendentes']??0,'hourglass-split'],['Cancelados no mês',$metrics['cancelados']??0,'x-circle'],['Concluídos no mês',$metrics['concluidos_mes']??0,'stars']] as [$label,$value,$icon]):?>
<article class="metric"><div class="metric-top"><span><?=e($label)?></span><span class="metric-icon"><i class="bi bi-<?=e($icon)?>"></i></span></div><strong><?=e((int)$value)?></strong></article><?php endforeach;?>
</section>
<div class="grid-main"><section class="panel"><header class="panel-header"><h2><i class="bi bi-calendar3 me-2"></i>Agenda</h2><div class="filters" data-calendar-filters><?php if(App\Core\Auth::role()!=='profissional'):?><select name="profissional_id" aria-label="Filtrar por profissional"><option value="">Todos os profissionais</option><?php foreach($professionals as $professional):?><option value="<?=e($professional['id'])?>"><?=e($professional['nome'])?></option><?php endforeach;?></select><?php endif;?><select name="servico_id" aria-label="Filtrar por serviço"><option value="">Todos os serviços</option><?php foreach($services as $service):?><option value="<?=e($service['id'])?>"><?=e($service['nome'])?></option><?php endforeach;?></select><select name="status" aria-label="Filtrar por status"><option value="">Todos os status</option><?php foreach(['pendente'=>'A confirmar','confirmado'=>'Confirmado','em_atendimento'=>'Em atendimento','concluido'=>'Concluído','cancelado'=>'Cancelado','nao_compareceu'=>'Não compareceu'] as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></div></header><div class="panel-body"><div class="calendar-status-legend" aria-label="Legenda dos status"><span><i class="status-dot status-pendente"></i>A confirmar</span><span><i class="status-dot status-confirmado"></i>Confirmado</span><span><i class="status-dot status-cancelado"></i>Cancelado</span></div><div data-calendar></div></div></section>
<aside class="panel"><header class="panel-header"><h2>Próximos atendimentos</h2><a href="<?=e(url('/agendamentos/novo'))?>" class="button small">Adicionar</a></header><div class="panel-body"><?php if($upcoming):?><div class="timeline"><?php foreach($upcoming as $item):?><a class="timeline-item" href="<?=e(url('/agendamentos/'.$item['id']))?>"><time><?=e(local_datetime($item['inicio_at'],$company['timezone'],'H:i'))?></time><span class="timeline-line"></span><span><strong><?=e($item['cliente_nome'])?></strong><small class="subtle"><?=e(local_datetime($item['inicio_at'],$company['timezone'],'d/m'))?> · <?=e($item['servico_nome'])?><br><?=e($item['profissional_nome'])?></small></span></a><?php endforeach;?></div><?php else:?><div class="empty"><i class="bi bi-calendar2-heart"></i><strong>Agenda livre por enquanto</strong><p>Os próximos agendamentos aparecerão aqui.</p></div><?php endif;?></div></aside></div>
<?php $content=ob_get_clean(); require BASE_PATH.'/resources/views/layouts/app.php'; ?>
